### ISSUE TITLE
Move Terrain shaders to game project

### ISSUE THREAD

**Issue by TimVinkemeier** [TimVinkemeier/SkiManager#2]
These shaders do not really belong to the engine, so move them to the game project.

**Comment by SvenEV** [comment]
OK, but TerrainBehavior (and associated types) should remain in the engine

**Comment by TimVinkemeier** [comment]
Agreed :wink:

**Comment by SvenEV** [comment]
Will fix this soon&trade; :D

**Comment by TimVinkemeier** [comment]
:+1:
